name: "testing2"
on: push

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Testing
        uses: jamie-pate/run-gut-tests-action@v2.0.3
        with:
          containerImage: barichello/godot-ci:latest
          useContainer: false
          godotFlags: --headless
          gutConfigpath: tests/.gutconfig.json
      
