name: "testing2"
on: push

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Testing
        uses: Hypasist/run-gut-tests-action@v1.0
        with:
          containerImage: barichello/godot-ci:latest
          useContainer: true
          godotFlags: --headless
          directory: /home/runner/work/Fantalone/Fantalone
          gutConfigpath: test/.gutconfig.json
          importGodotResources: true
      
