name: "Godot Unit Testing"
on: push

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Demo Action
        uses: Hypasist/action-demo@f3270a6b158a1579da3a1a99fb78e8d3266068fd
      - name: Testing
        uses: Hypasist/run-gut-tests-action-butdifferent@v0
        with:
          containerImage: barichello/godot-ci:latest
          useContainer: true
          godotFlags: --headless
          directory: /home/runner/work/Fantalone/Fantalone
          gutConfigpath: test/.gutconfig.json
          importGodotResources: true
      
